name: Pytest

on:
  push:
    branches:
      - master

  pull_request:

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: # Add this block
      contents: write # Grant write permission for repository contents

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        run: uv run pytest --cov=yupy --cov-report term --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
